numpy=1.13.3
altair=1.2.1
bokeh=0.12.13
boto3=1.4.7
Cython=0.27.3
h5py=2.7.1
jupyter=1.0.0
jupyterlab=0.30.6
matplotlib=2.1.1
numba=0.35.0
numpy=1.13.3
pandas=0.21.0
scikit-learn=0.19.1
scipy=1.0.0
seaborn=0.8.1
SQLAlchemy=1.1.13
statsmodels=0.8.0
sympy=1.1.1
hdf5=1.10.1
arrow-cpp=0.7.1
parquet-cpp=1.3.0.post